pipeline{
    agent{
        label 'AGENT-1'
    }
    options{
        timeout(time: 10, unit: 'SECONDS')
        disableConcurrentBuilds()

    }

    environment{
        TRINER = "SIVA"
    }

    parameters {
        string(name: 'PERSON', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')

        text(name: 'BIOGRAPHY', defaultValue: '', description: 'Enter some information about the person')

        booleanParam(name: 'DEPLOY', defaultValue: false, description: 'Deployment check the box')

        choice(name: 'CHOICE', choices: ['One', 'Two', 'Three'], description: 'Pick something')

        password(name: 'PASSWORD', defaultValue: 'SECRET', description: 'Enter a password')
    }

    stages{

        stage('Example') {
            steps {
                script{
                    sh """
                echo "Hello ${params.PERSON}"

                echo "Biography: ${params.BIOGRAPHY}"

                echo "Toggle: ${params.DEPLOY}"

                echo "Choice: ${params.CHOICE}"

                echo "Password: ${params.PASSWORD}"
                
                """
                }
            }
        }
        stage('Build'){
            steps{
                script{
                    sh """
                echo "this is build"
                env                 // default variables we can use it
                """
            }
            }
        }

         stage('Test'){
            steps{
                sh 'echo this is Test'
                echo $TRINER
            }
        }

         stage('Deploy'){

            //      input {
            //     message "Should we continue?"
            //     ok "Yes, we should."
            //     submitter "alice,bob"
            //     parameters {
            //         string(name: 'PERSON', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')
            //     }
            // }

            when{
                expression{"$params.DEPLOY" == "true"}
            }
            steps{
                script{
                    sh """
            
               echo 'this is deploy'
                
                """
            }
            }
        }
    }
post{
    always{
        echo "i am alsways executes"
        cleanWs()
    }
    failure{
        echo "i execute when i failed"
    }
    success{
        echo "sucesss"
    }
    aborted{
        echo "the pipeline is aborted due to time exceeded"
    }
}
}