pipeline{
    agent{
        label 'AGENT-1'
    }
    stages{
        stage('Build'){
            steps{
                sh 'echo this is build'
            }
        }

         stage('Test'){
            steps{
                sh 'echo this is Test'
            }
        }

         stage('Deploy'){
            steps{
                sh 'echo this is deploy'
            }
        }
    }
post{
    always{
        echo "i am alsways executes"
        cleanWs()
    }
    failure{
        echo "i execute when i failed"
    }
    success{
        echo "sucesss"
    }
}
}